In [3]:
#실습문제 1

import csv

f = open('seoul.csv','r',encoding='cp949')
data = csv.reader(f, delimiter=',')
header = next(data)
max_temp = -999
max_date = ''
min_temp = 999
min_date = ''
max_dif = 0
max_dif_date = ''
dif = 0
for row in data:
    if row[-1] == '':
        row[-1] = -999
        dif = -1
    row[-1] = float(row[-1])
    if max_temp < row[-1]:
        max_date = row[0]
        max_temp = row[-1]
    if row[-2] == '':
        row[-2] = 999
        dif = -1
    row[-2] = float(row[-2])
    if min_temp > row[-2]:
        min_date = row[0]
        min_temp = row[-2]
    if dif != -1:
        dif = row[-1] - row[-2]
        if max_dif < dif:
            max_dif_date = row[0]
            max_dif = dif
print('일교차가 가장 큰 날')
print(max_dif_date + " " + str(max_temp))
print('최저기온이 가장 낮은 날')
print(min_date + " " + str(min_temp))
print('최고기온이 가장 높은 날')
print(max_date + " " + str(max_dif))
f.close()

일교차가 가장 큰 날
2021-04-21 36.5
최저기온이 가장 낮은 날
2021-01-08 -18.6
최고기온이 가장 높은 날
2021-07-24 17.9

In [14]:
#실습문제 2

import csv

f = open('subway.csv','r',encoding='cp949')
data = csv.reader(f, delimiter=',')
header = next(data)
pre = '1호선'
mx = [-1]*3
mn = [999999999]*3
mx_station = ['']*4
mn_station = ['']*4
for row in data:
    if pre != row[1]:
        print(pre)
        print('이용객이 가장 많은 역 순위')
        for i in range(3):
            print(str(i+1)+'. '+mx_station[i]+'('+str(mx[i])+')')
        print('이용객이 가장 적은 역 순위')
        for i in range(3):
            print(str(i+1)+'. '+mn_station[i]+'('+str(mn[i])+')')
        mx = [-1]*3
        mn = [999999999]*3
        mx_station = ['']*4
        mn_station = ['']*4
    
    row[-1] = row[-1].replace(",","")
    row[-2] = row[-2].replace(",","")
    count = int(row[-1]) + int(row[-2])
    for i in range(0,3):
        if(mx[i] < count):
            for j in range(2,i,-1):
                mx[j] = mx[j-1]
                mx_station[j] = mx_station[j-1]
            mx[i] = count
            mx_station[i] = row[3] + ' ' + row[1]
            break
    for i in range(0,3):
        if(mn[i] > count):
            for j in range(2,i,-1):
                mn[j] = mn[j-1]
                mn_station[j] = mn_station[j-1]
            mn[i] = count
            mn_station[i] = row[3] + ' ' + row[1]
            break
    pre = row[1]
f.close()

1호선
이용객이 가장 많은 역 순위
1. 서울역 1호선(2324817)
2. 종각 1호선(1721553)
3. 종로3가 1호선(1267098)
이용객이 가장 적은 역 순위
1. 동묘앞 1호선(477540)
2. 동대문 1호선(598363)
3. 신설동 1호선(715381)
2호선
이용객이 가장 많은 역 순위
1. 강남 2호선(4364436)
2. 잠실(송파구청) 2호선(3927922)
3. 신림 2호선(3412199)
이용객이 가장 적은 역 순위
1. 도림천 2호선(73495)
2. 신답 2호선(92368)
3. 용두(동대문구청) 2호선(130447)
3호선
이용객이 가장 많은 역 순위
1. 고속터미널 3호선(2393331)
2. 양재(서초구청) 3호선(2098334)
3. 연신내 3호선(1933410)
이용객이 가장 적은 역 순위
1. 충무로 3호선(24)
2. 학여울 3호선(110564)
3. 무악재 3호선(208517)
4호선
이용객이 가장 많은 역 순위
1. 수유(강북구청) 4호선(1852687)
2. 혜화 4호선(1806760)
3. 쌍문 4호선(1523740)
이용객이 가장 적은 역 순위
1. 남태령 4호선(61860)
2. 동작(현충원) 4호선(78275)
3. 삼각지 4호선(280235)
경부선
이용객이 가장 많은 역 순위
1. 영등포 경부선(2256385)
2. 수원 경부선(2081264)
3. 용산 경부선(2032713)
이용객이 가장 적은 역 순위
1. 직산 경부선(42371)
2. 서동탄 경부선(72294)
3. 진위 경부선(82663)
경인선
이용객이 가장 많은 역 순위
1. 부천 경인선(1799939)
2. 부평 경인선(1711637)
3. 역곡 경인선(1445062)
이용객이 가장 적은 역 순위
1. 도원 경인선(158971)
2. 인천 경인선(165660)
3. 도화 경인선(219427)
경원선
이용객이 가장 많은 역 순위
1. 의정부 경원선(1063474)
2. 청량리(서울시립대입구) 경원선(890191)
3. 왕십리(성동구청) 경원선(836361)
이용객이 가장 적은 역 순위
1. 창동 경원선(8)
2. 옥수 경원선(2479)
3. 보산 경원선(88930)
안산선
이용객이 가장 많은 역 순위
1. 중앙 안산선(1001865)
2. 산본 안산선(877376)
3. 상록수 안산선(862050)
이용객이 가장 적은 역 순위
1. 신길온천 안산선(91223)
2. 수리산 안산선(206899)
3. 반월 안산선(228805)
과천선
이용객이 가장 많은 역 순위
1. 범계 과천선(1396198)
2. 인덕원 과천선(1296642)
3. 평촌 과천선(915529)
이용객이 가장 적은 역 순위
1. 대공원 과천선(137405)
2. 경마공원 과천선(205207)
3. 과천 과천선(308984)
분당선
이용객이 가장 많은 역 순위
1. 야탑 분당선(1425589)
2. 서현 분당선(1392273)
3. 압구정로데오 분당선(1143825)
이용객이 가장 적은 역 순위
1. 복정 분당선(16)
2. 구룡 분당선(107611)
3. 보정 분당선(124121)
일산선
이용객이 가장 많은 역 순위
1. 삼송 일산선(1027489)
2. 화정 일산선(931354)
3. 대화 일산선(629563)
이용객이 가장 적은 역 순위
1. 지축 일산선(11)
2. 대곡 일산선(91209)
3. 마두 일산선(402870)
중앙선
이용객이 가장 많은 역 순위
1. 회기 중앙선(1307591)
2. 구리 중앙선(735703)
3. 도농 중앙선(535443)
이용객이 가장 적은 역 순위
1. 지평 중앙선(3468)
2. 신원 중앙선(10068)
3. 오빈 중앙선(15390)
장항선
이용객이 가장 많은 역 순위
1. 온양온천 장항선(203279)
2. 아산 장항선(172291)
3. 쌍용(나사렛대) 장항선(110434)
이용객이 가장 적은 역 순위
1. 탕정 장항선(20015)
2. 배방 장항선(55684)
3. 봉명 장항선(59620)
경의선
이용객이 가장 많은 역 순위
1. 일산 경의선(496084)
2. 행신 경의선(421559)
3. 탄현 경의선(405138)
이용객이 가장 적은 역 순위
1. 검암 경의선(2)
2. 계양 경의선(8)
3. 임진강 경의선(1032)
경춘선
이용객이 가장 많은 역 순위
1. 평내호평 경춘선(322875)
2. 마석 경춘선(206377)
3. 퇴계원 경춘선(185661)
이용객이 가장 적은 역 순위
1. 굴봉산 경춘선(7460)
2. 백양리 경춘선(12058)
3. 상천 경춘선(12458)
수인선
이용객이 가장 많은 역 순위
1. 인하대 수인선(310934)
2. 인천논현 수인선(307373)
3. 소래포구 수인선(275581)
이용객이 가장 적은 역 순위
1. 달월 수인선(4426)
2. 야목 수인선(15389)
3. 어천 수인선(40562)
경강선
이용객이 가장 많은 역 순위
1. 경기광주 경강선(397527)
2. 판교 경강선(252872)
3. 초월 경강선(164862)
이용객이 가장 적은 역 순위
1. 세종대왕릉 경강선(16870)
2. 이매 경강선(55608)
3. 신둔도예촌 경강선(75801)
5호선
이용객이 가장 많은 역 순위
1. 광화문(세종문화회관) 5호선(1585762)
2. 까치산 5호선(1536307)
3. 화곡 5호선(1474473)
이용객이 가장 적은 역 순위
1. 동대문역사문화공원(DDP) 5호선(158553)
2. 오금 5호선(196258)
3. 영등포구청 5호선(198914)
6호선
이용객이 가장 많은 역 순위
1. 응암 6호선(943562)
2. 공덕 6호선(934075)
3. 망원 6호선(810198)
이용객이 가장 적은 역 순위
1. 신내 6호선(8)
2. 연신내 6호선(26)
3. 버티고개 6호선(106297)
7호선
이용객이 가장 많은 역 순위
1. 가산디지털단지 7호선(2272388)
2. 학동 7호선(1278185)
3. 광명사거리 7호선(1214033)
이용객이 가장 적은 역 순위
1. 장암 7호선(85870)
2. 부천종합운동장 7호선(251904)
3. 삼산체육관 7호선(278885)
8호선
이용객이 가장 많은 역 순위
1. 문정 8호선(1130604)
2. 암사 8호선(955640)
3. 장지 8호선(924809)
이용객이 가장 적은 역 순위
1. 남위례 8호선(85989)
2. 모란 8호선(226139)
3. 신흥 8호선(249610)
9호선
이용객이 가장 많은 역 순위
1. 신논현 9호선(1735678)
2. 노량진 9호선(1395307)
3. 여의도 9호선(1344192)
이용객이 가장 적은 역 순위
1. 구반포 9호선(88309)
2. 동작(현충원) 9호선(88773)
3. 개화 9호선(110832)
공항철도 1호선
이용객이 가장 많은 역 순위
1. 디지털미디어시티 공항철도 1호선(657629)
2. 홍대입구 공항철도 1호선(579505)
3. 김포공항 공항철도 1호선(547843)
이용객이 가장 적은 역 순위
1. 인천공항2터미널 공항철도 1호선(126634)
2. 공항화물청사 공항철도 1호선(126647)
3. 공덕 공항철도 1호선(141992)
9호선2~3단계
이용객이 가장 많은 역 순위
1. 봉은사 9호선2~3단계(931073)
2. 언주 9호선2~3단계(567179)
3. 선정릉 9호선2~3단계(512992)
이용객이 가장 적은 역 순위
1. 둔촌오륜 9호선2~3단계(59273)
2. 한성백제 9호선2~3단계(130968)
3. 종합운동장 9호선2~3단계(218810)